version: '3.8'

services:
  # Servicio del BACKEND
  temperaturas-backend:
    build: 
      context: ./backend
    container_name: temperaturas-backend
    restart: always
    
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  # Servicio del FRONTEND
  temperaturas-frontend:
    build: 
      context: ./frontend
    container_name: temperaturas-frontend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - TEMP_SERVER=temperaturas-backend:5000
    depends_on:
      - temperaturas-backend
